# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    # ...
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"

    configs:
        my_config:
            language: ru
            filebrowserUploadRoute: "market.uploads.upload"
            extraPlugins: "div"
            allowedContent: true

    plugins:
        div:
            path: "build/ckeditor/plugins/div/" # with trailing slash
            filename: "plugin.js"

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
